modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Effect-Tooltips/issues"
license="LGPL v2.1"

[[mods]]
modId="effecttooltips"
updateJSONURL="https://updates.blamejared.com/get?n=effecttooltips&gv=1.16.5"
version="${version}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:name_tag"

[[dependencies.effecttooltips]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="CLIENT"

[[dependencies.effecttooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"